/*******************************************************************************
* File Name: cyfitter_sysint.h
* 
* PSoC Creator  4.2
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_SYSINT_H
#define INCLUDED_CYFITTER_SYSINT_H
#include "cy_device_headers.h"

/* Shake_IRQ */
#define Shake_IRQ__INTC_CORTEXM0P_ASSIGNED 1
#define Shake_IRQ__INTC_CORTEXM0P_MUX 14u
#define Shake_IRQ__INTC_CORTEXM0P_PRIORITY 3u
#define Shake_IRQ__INTC_NUMBER 123u
#define Shake_IRQ_INTC_CORTEXM0P_ASSIGNED 1
#define Shake_IRQ_INTC_CORTEXM0P_MUX 14u
#define Shake_IRQ_INTC_CORTEXM0P_PRIORITY 3u
#define Shake_IRQ_INTC_NUMBER 123u

/* Press1_IRQ */
#define Press1_IRQ__INTC_CORTEXM0P_ASSIGNED 1
#define Press1_IRQ__INTC_CORTEXM0P_MUX 3u
#define Press1_IRQ__INTC_CORTEXM0P_PRIORITY 3u
#define Press1_IRQ__INTC_NUMBER 7u
#define Press1_IRQ_INTC_CORTEXM0P_ASSIGNED 1
#define Press1_IRQ_INTC_CORTEXM0P_MUX 3u
#define Press1_IRQ_INTC_CORTEXM0P_PRIORITY 3u
#define Press1_IRQ_INTC_NUMBER 7u

/* WatchDog_IRQ */
#define WatchDog_IRQ__INTC_CORTEXM0P_ASSIGNED 1
#define WatchDog_IRQ__INTC_CORTEXM0P_MUX 5u
#define WatchDog_IRQ__INTC_CORTEXM0P_PRIORITY 3u
#define WatchDog_IRQ__INTC_NUMBER 19u
#define WatchDog_IRQ_INTC_CORTEXM0P_ASSIGNED 1
#define WatchDog_IRQ_INTC_CORTEXM0P_MUX 5u
#define WatchDog_IRQ_INTC_CORTEXM0P_PRIORITY 3u
#define WatchDog_IRQ_INTC_NUMBER 19u

/* AppControl_IRQ */
#define AppControl_IRQ__INTC_CORTEXM0P_ASSIGNED 1
#define AppControl_IRQ__INTC_CORTEXM0P_MUX 9u
#define AppControl_IRQ__INTC_CORTEXM0P_PRIORITY 3u
#define AppControl_IRQ__INTC_NUMBER 122u
#define AppControl_IRQ_INTC_CORTEXM0P_ASSIGNED 1
#define AppControl_IRQ_INTC_CORTEXM0P_MUX 9u
#define AppControl_IRQ_INTC_CORTEXM0P_PRIORITY 3u
#define AppControl_IRQ_INTC_NUMBER 122u

/* ChimeTimer_IRQ */
#define ChimeTimer_IRQ__INTC_CORTEXM0P_ASSIGNED 1
#define ChimeTimer_IRQ__INTC_CORTEXM0P_MUX 10u
#define ChimeTimer_IRQ__INTC_CORTEXM0P_PRIORITY 3u
#define ChimeTimer_IRQ__INTC_NUMBER 93u
#define ChimeTimer_IRQ_INTC_CORTEXM0P_ASSIGNED 1
#define ChimeTimer_IRQ_INTC_CORTEXM0P_MUX 10u
#define ChimeTimer_IRQ_INTC_CORTEXM0P_PRIORITY 3u
#define ChimeTimer_IRQ_INTC_NUMBER 93u

/* LightTimer_IRQ */
#define LightTimer_IRQ__INTC_CORTEXM0P_ASSIGNED 1
#define LightTimer_IRQ__INTC_CORTEXM0P_MUX 11u
#define LightTimer_IRQ__INTC_CORTEXM0P_PRIORITY 3u
#define LightTimer_IRQ__INTC_NUMBER 92u
#define LightTimer_IRQ_INTC_CORTEXM0P_ASSIGNED 1
#define LightTimer_IRQ_INTC_CORTEXM0P_MUX 11u
#define LightTimer_IRQ_INTC_CORTEXM0P_PRIORITY 3u
#define LightTimer_IRQ_INTC_NUMBER 92u

/* MotorTimer_IRQ */
#define MotorTimer_IRQ__INTC_CORTEXM0P_ASSIGNED 1
#define MotorTimer_IRQ__INTC_CORTEXM0P_MUX 12u
#define MotorTimer_IRQ__INTC_CORTEXM0P_PRIORITY 3u
#define MotorTimer_IRQ__INTC_NUMBER 95u
#define MotorTimer_IRQ_INTC_CORTEXM0P_ASSIGNED 1
#define MotorTimer_IRQ_INTC_CORTEXM0P_MUX 12u
#define MotorTimer_IRQ_INTC_CORTEXM0P_PRIORITY 3u
#define MotorTimer_IRQ_INTC_NUMBER 95u

/* SensorBus_SCB_IRQ */
#define SensorBus_SCB_IRQ__INTC_CORTEXM0P_ASSIGNED 1
#define SensorBus_SCB_IRQ__INTC_CORTEXM0P_MUX 13u
#define SensorBus_SCB_IRQ__INTC_CORTEXM0P_PRIORITY 1u
#define SensorBus_SCB_IRQ__INTC_NUMBER 47u
#define SensorBus_SCB_IRQ_INTC_CORTEXM0P_ASSIGNED 1
#define SensorBus_SCB_IRQ_INTC_CORTEXM0P_MUX 13u
#define SensorBus_SCB_IRQ_INTC_CORTEXM0P_PRIORITY 1u
#define SensorBus_SCB_IRQ_INTC_NUMBER 47u

/* UART_DEBUG_SCB_IRQ */
#define UART_DEBUG_SCB_IRQ__INTC_CORTEXM0P_ASSIGNED 1
#define UART_DEBUG_SCB_IRQ__INTC_CORTEXM0P_MUX 8u
#define UART_DEBUG_SCB_IRQ__INTC_CORTEXM0P_PRIORITY 3u
#define UART_DEBUG_SCB_IRQ__INTC_NUMBER 46u
#define UART_DEBUG_SCB_IRQ_INTC_CORTEXM0P_ASSIGNED 1
#define UART_DEBUG_SCB_IRQ_INTC_CORTEXM0P_MUX 8u
#define UART_DEBUG_SCB_IRQ_INTC_CORTEXM0P_PRIORITY 3u
#define UART_DEBUG_SCB_IRQ_INTC_NUMBER 46u

/* Bluetooth_bless_isr */
#define Bluetooth_bless_isr__INTC_CORTEXM0P_ASSIGNED 1
#define Bluetooth_bless_isr__INTC_CORTEXM0P_MUX 4u
#define Bluetooth_bless_isr__INTC_CORTEXM0P_PRIORITY 1u
#define Bluetooth_bless_isr__INTC_NUMBER 24u
#define Bluetooth_bless_isr_INTC_CORTEXM0P_ASSIGNED 1
#define Bluetooth_bless_isr_INTC_CORTEXM0P_MUX 4u
#define Bluetooth_bless_isr_INTC_CORTEXM0P_PRIORITY 1u
#define Bluetooth_bless_isr_INTC_NUMBER 24u

#endif /* INCLUDED_CYFITTER_SYSINT_H */
