/*******************************************************************************
* File Name: cyfitter_sysint_cfg.h
* 
* PSoC Creator  4.2
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_SYSINT_CFG_H
#define INCLUDED_CYFITTER_SYSINT_CFG_H

#include "sysint/cy_sysint.h"

/* ARM CM0+ */
#if (((__CORTEX_M == 0) && (CY_CORE_ID == 0)))
    #define Press1_IRQ__INTC_ASSIGNED 1u
    extern const cy_stc_sysint_t Press1_IRQ_cfg;

    #define WatchDog_IRQ__INTC_ASSIGNED 1u
    extern const cy_stc_sysint_t WatchDog_IRQ_cfg;

    #define Bluetooth_bless_isr__INTC_ASSIGNED 1u
    extern const cy_stc_sysint_t Bluetooth_bless_isr_cfg;

    #define SensorBus_SCB_IRQ__INTC_ASSIGNED 1u
    extern const cy_stc_sysint_t SensorBus_SCB_IRQ_cfg;

    #define UART_DEBUG_SCB_IRQ__INTC_ASSIGNED 1u
    extern const cy_stc_sysint_t UART_DEBUG_SCB_IRQ_cfg;

    #define LightTimer_IRQ__INTC_ASSIGNED 1u
    extern const cy_stc_sysint_t LightTimer_IRQ_cfg;

    #define ChimeTimer_IRQ__INTC_ASSIGNED 1u
    extern const cy_stc_sysint_t ChimeTimer_IRQ_cfg;

    #define MotorTimer_IRQ__INTC_ASSIGNED 1u
    extern const cy_stc_sysint_t MotorTimer_IRQ_cfg;

    #define AppControl_IRQ__INTC_ASSIGNED 1u
    extern const cy_stc_sysint_t AppControl_IRQ_cfg;

    #define Shake_IRQ__INTC_ASSIGNED 1u
    extern const cy_stc_sysint_t Shake_IRQ_cfg;

#endif /* ((__CORTEX_M == 0) && (CY_CORE_ID == 0)) */

/* ARM CM4 */
#if (((__CORTEX_M == 4) && (CY_CORE_ID == 0)))
    #define ADC_IRQ__INTC_ASSIGNED 1u
    extern const cy_stc_sysint_t ADC_IRQ_cfg;

#endif /* ((__CORTEX_M == 4) && (CY_CORE_ID == 0)) */


#endif /* INCLUDED_CYFITTER_SYSINT_CFG_H */
