/*******************************************************************************
* File Name: cyfitter_sysint_cfg.c
* 
* PSoC Creator  4.2
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_sysint.h"
#include "cyfitter_sysint_cfg.h"

/* ARM CM0+ */
#if (((__CORTEX_M == 0) && (CY_CORE_ID == 0)))

    /* Press1_IRQ */
    const cy_stc_sysint_t Press1_IRQ_cfg = {
        .intrSrc = (IRQn_Type)Press1_IRQ__INTC_CORTEXM0P_MUX,
        .cm0pSrc = (cy_en_intr_t)Press1_IRQ__INTC_NUMBER,
        .intrPriority = Press1_IRQ__INTC_CORTEXM0P_PRIORITY
    };

    /* WatchDog_IRQ */
    const cy_stc_sysint_t WatchDog_IRQ_cfg = {
        .intrSrc = (IRQn_Type)WatchDog_IRQ__INTC_CORTEXM0P_MUX,
        .cm0pSrc = (cy_en_intr_t)WatchDog_IRQ__INTC_NUMBER,
        .intrPriority = WatchDog_IRQ__INTC_CORTEXM0P_PRIORITY
    };

    /* Bluetooth_bless_isr */
    const cy_stc_sysint_t Bluetooth_bless_isr_cfg = {
        .intrSrc = (IRQn_Type)Bluetooth_bless_isr__INTC_CORTEXM0P_MUX,
        .cm0pSrc = (cy_en_intr_t)Bluetooth_bless_isr__INTC_NUMBER,
        .intrPriority = Bluetooth_bless_isr__INTC_CORTEXM0P_PRIORITY
    };

    /* SensorBus_SCB_IRQ */
    const cy_stc_sysint_t SensorBus_SCB_IRQ_cfg = {
        .intrSrc = (IRQn_Type)SensorBus_SCB_IRQ__INTC_CORTEXM0P_MUX,
        .cm0pSrc = (cy_en_intr_t)SensorBus_SCB_IRQ__INTC_NUMBER,
        .intrPriority = SensorBus_SCB_IRQ__INTC_CORTEXM0P_PRIORITY
    };

    /* UART_DEBUG_SCB_IRQ */
    const cy_stc_sysint_t UART_DEBUG_SCB_IRQ_cfg = {
        .intrSrc = (IRQn_Type)UART_DEBUG_SCB_IRQ__INTC_CORTEXM0P_MUX,
        .cm0pSrc = (cy_en_intr_t)UART_DEBUG_SCB_IRQ__INTC_NUMBER,
        .intrPriority = UART_DEBUG_SCB_IRQ__INTC_CORTEXM0P_PRIORITY
    };

    /* CapSense_ISR */
    const cy_stc_sysint_t CapSense_ISR_cfg = {
        .intrSrc = (IRQn_Type)CapSense_ISR__INTC_CORTEXM0P_MUX,
        .cm0pSrc = (cy_en_intr_t)CapSense_ISR__INTC_NUMBER,
        .intrPriority = CapSense_ISR__INTC_CORTEXM0P_PRIORITY
    };

    /* LightTimer_IRQ */
    const cy_stc_sysint_t LightTimer_IRQ_cfg = {
        .intrSrc = (IRQn_Type)LightTimer_IRQ__INTC_CORTEXM0P_MUX,
        .cm0pSrc = (cy_en_intr_t)LightTimer_IRQ__INTC_NUMBER,
        .intrPriority = LightTimer_IRQ__INTC_CORTEXM0P_PRIORITY
    };

    /* ChimeTimer_IRQ */
    const cy_stc_sysint_t ChimeTimer_IRQ_cfg = {
        .intrSrc = (IRQn_Type)ChimeTimer_IRQ__INTC_CORTEXM0P_MUX,
        .cm0pSrc = (cy_en_intr_t)ChimeTimer_IRQ__INTC_NUMBER,
        .intrPriority = ChimeTimer_IRQ__INTC_CORTEXM0P_PRIORITY
    };

    /* MotorTimer_IRQ */
    const cy_stc_sysint_t MotorTimer_IRQ_cfg = {
        .intrSrc = (IRQn_Type)MotorTimer_IRQ__INTC_CORTEXM0P_MUX,
        .cm0pSrc = (cy_en_intr_t)MotorTimer_IRQ__INTC_NUMBER,
        .intrPriority = MotorTimer_IRQ__INTC_CORTEXM0P_PRIORITY
    };

    /* AppControl_IRQ */
    const cy_stc_sysint_t AppControl_IRQ_cfg = {
        .intrSrc = (IRQn_Type)AppControl_IRQ__INTC_CORTEXM0P_MUX,
        .cm0pSrc = (cy_en_intr_t)AppControl_IRQ__INTC_NUMBER,
        .intrPriority = AppControl_IRQ__INTC_CORTEXM0P_PRIORITY
    };

    /* Shake_IRQ */
    const cy_stc_sysint_t Shake_IRQ_cfg = {
        .intrSrc = (IRQn_Type)Shake_IRQ__INTC_CORTEXM0P_MUX,
        .cm0pSrc = (cy_en_intr_t)Shake_IRQ__INTC_NUMBER,
        .intrPriority = Shake_IRQ__INTC_CORTEXM0P_PRIORITY
    };

#endif /* ((__CORTEX_M == 0) && (CY_CORE_ID == 0)) */

